# 1. Pandas

In [1]:
import pandas as pd
import numpy as np
import random

# 2. 파일에서 데이터 불러오기

In [2]:
mushroom = pd.read_csv('mushrooms.csv')

In [3]:
mushroom.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [4]:
mushroom.tail()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

----------
# 3. DataFrame 생성하기

## (1) Dictionary

In [5]:
dictFriends = [
    {'name' : 'Lee', 'age' : 25, 'university' : 'Chung-Ang', 'major' : 'CS'},
    {'name' : 'David', 'age' : 28, 'university' : 'Stanford', 'major' : 'EE'},
    {'name' : 'Lee', 'age' : 25, 'university' : 'Chung-Ang', 'major' : 'CS' }
]

In [6]:
myFriends = pd.DataFrame(dictFriends)
myFriends

   age major   name university
0   25    CS    Lee  Chung-Ang
1   28    EE  David   Stanford
2   25    CS    Lee  Chung-Ang

In [7]:
# dict : column을 수동정렬 해야 함
myFriends = myFriends[['name', 'age', 'university', 'major']]
myFriends

    name  age university major
0    Lee   25  Chung-Ang    CS
1  David   28   Stanford    EE
2    Lee   25  Chung-Ang    CS

## (2) List

In [8]:
listFriends = [
    ['Lee', 25, 'Chung-Ang', 'CS'],
    ['David', 28, 'Stanford', 'EE'],
    ['Kim', 22, 'Seoul', 'BE']
]

columnName = ['name', 'age', 'university', 'major']

In [9]:
myFriends = pd.DataFrame.from_records(listFriends, columns = columnName)
myFriends

    name  age university major
0    Lee   25  Chung-Ang    CS
1  David   28   Stanford    EE
2    Kim   22      Seoul    BE

----------
# 4. DataFrame 파일로 저장하기

In [10]:
myFriends.to_csv('friends.csv', index = True, header = True)

----------
# 5. 행, 열 선택 및 필터

In [11]:
mushroom.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

## (1) Row Selection
+ **참조사이트** : http://yeyej.blogspot.com/2016/02/pandas-dataframe-iloc-loc-ix.html
+ **loc, iloc, ix**

In [12]:
# loc : label에 의한 Selection
mushroom.loc[[0, 3, 9]]

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
9,e,b,s,y,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,s,m

In [13]:
mushroom.loc[:4] # 값이 4인 애들까지 출력

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [14]:
# iloc : index에 의한 Selection
mushroom.iloc[:4] # index가 3인 애들까지 출력

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u

## (2) Row Selection by Condition

In [15]:
# 단일조건
temp = mushroom[mushroom.odor=='p']
temp.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
13,p,x,y,w,t,p,f,c,n,k,...,s,w,w,p,w,o,p,n,v,u
17,p,x,s,n,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,g

In [16]:
# 복합조건
temp = mushroom[(mushroom.bruises=='t') & (mushroom.odor=='p')]
temp.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
13,p,x,y,w,t,p,f,c,n,k,...,s,w,w,p,w,o,p,n,v,u
17,p,x,s,n,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,g

## (3) Column Selection by Filter
+ **items, like, regex**

In [17]:
temp = mushroom.filter(items = ['odor', 'population'])
temp.head()

  odor population
0    p          s
1    a          n
2    l          n
3    p          s
4    n          a

In [18]:
temp = mushroom.filter(like = 'cap', axis = 1)
temp.head()

  cap-shape cap-surface cap-color
0         x           s         n
1         x           s         y
2         b           s         w
3         x           y         w
4         x           s         g

In [19]:
temp = mushroom.filter(regex='color$', axis = 1)
temp.head()

  cap-color gill-color veil-color spore-print-color
0         n          k          w                 k
1         y          k          w                 n
2         w          n          w                 n
3         w          n          w                 k
4         g          k          w                 n

----------
# 6. 행, 열 삭제

## (1) Row Deletion

In [20]:
# drop : 해당 label의 row를 제거함
temp = mushroom.drop([0, 3, 5])
temp.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
6,e,b,s,w,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,n,m
7,e,b,y,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,s,m

In [21]:
# inplace : 리턴값이 바로 적용됨 -> 따로 대입할 필요 없음
temp.drop([2, 4, 6], inplace = True)
temp.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
7,e,b,y,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,s,m
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
9,e,b,s,y,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,s,m
10,e,x,y,y,t,l,f,c,b,g,...,s,w,w,p,w,o,p,n,n,g

In [22]:
# index : 해당 label이 아닌 index의 row를 제거함
temp.drop(temp.index[:4], inplace = True)
temp.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
10,e,x,y,y,t,l,f,c,b,g,...,s,w,w,p,w,o,p,n,n,g
11,e,x,y,y,t,a,f,c,b,n,...,s,w,w,p,w,o,p,k,s,m
12,e,b,s,y,t,a,f,c,b,w,...,s,w,w,p,w,o,p,n,s,g
13,p,x,y,w,t,p,f,c,n,k,...,s,w,w,p,w,o,p,n,v,u
14,e,x,f,n,f,n,f,w,b,n,...,f,w,w,p,w,o,e,k,a,g

## (2) Column Deletion

In [23]:
# axis = 1 : Column을 의미!!
temp = temp.drop('cap-surface', axis=1)
temp.head()

,class,cap-shape,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
10,e,x,y,t,l,f,c,b,g,e,...,s,w,w,p,w,o,p,n,n,g
11,e,x,y,t,a,f,c,b,n,e,...,s,w,w,p,w,o,p,k,s,m
12,e,b,y,t,a,f,c,b,w,e,...,s,w,w,p,w,o,p,n,s,g
13,p,x,w,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,n,v,u
14,e,x,n,f,n,f,w,b,n,t,...,f,w,w,p,w,o,e,k,a,g

----------
# 7. 행, 열 생성 및 수정

## (1) Column Creating

In [24]:
# df['name'] : 해당 name의 column을 dataframe에 추가
mushroom['price'] = 1
mushroom.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,price
0,p,x,s,n,t,p,f,c,n,k,...,w,w,p,w,o,p,k,s,u,1
1,e,x,s,y,t,a,f,c,b,k,...,w,w,p,w,o,p,n,n,g,1
2,e,b,s,w,t,l,f,c,b,n,...,w,w,p,w,o,p,n,n,m,1
3,p,x,y,w,t,p,f,c,n,n,...,w,w,p,w,o,p,k,s,u,1
4,e,x,s,g,f,n,f,w,b,k,...,w,w,p,w,o,e,n,a,g,1

In [25]:
# np.where을 활용해 새 Column에 Value Assign
# Q) where문 안에 '복합조건'을 사용할 수 없는가?
mushroom['rarity'] = np.where(mushroom['habitat'] == 'u', 'high', 'low')
mushroom.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,price,rarity
0,p,x,s,n,t,p,f,c,n,k,...,w,p,w,o,p,k,s,u,1,high
1,e,x,s,y,t,a,f,c,b,k,...,w,p,w,o,p,n,n,g,1,low
2,e,b,s,w,t,l,f,c,b,n,...,w,p,w,o,p,n,n,m,1,low
3,p,x,y,w,t,p,f,c,n,n,...,w,p,w,o,p,k,s,u,1,high
4,e,x,s,g,f,n,f,w,b,k,...,w,p,w,o,e,n,a,g,1,low

## (2) Column Modifying

In [26]:
# 먹을 수 있으면 높게, 그렇지 않으면 낮게 가치측정
def price_calculating(row) :
    if row == 'e':
        return random.randint(30, 80)
    else:
        return random.randint(0, 10)

In [27]:
# class column에 함수 apply해서 price column을 생성하고 값 삽입
mushroom['price'] = mushroom['class'].apply(price_calculating)

In [28]:
mushroom.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,price,rarity
0,p,x,s,n,t,p,f,c,n,k,...,w,p,w,o,p,k,s,u,7,high
1,e,x,s,y,t,a,f,c,b,k,...,w,p,w,o,p,n,n,g,75,low
2,e,b,s,w,t,l,f,c,b,n,...,w,p,w,o,p,n,n,m,67,low
3,p,x,y,w,t,p,f,c,n,n,...,w,p,w,o,p,k,s,u,3,high
4,e,x,s,g,f,n,f,w,b,k,...,w,p,w,o,e,n,a,g,31,low

## (3) Row Creating

In [29]:
students = [
    ['James', '25', '100', '87'],
    ['Kafka', '32', '80', '79'],
    ['Viera', '27', '90', '65'],
    ['Phobe', '18', '60', '78']
]
column_name = ['Name', 'Age', 'Midterm', 'Final']

In [30]:
df = pd.DataFrame.from_records(students, columns = column_name)

In [31]:
df.head()

    Name Age Midterm Final
0  James  25     100    87
1  Kafka  32      80    79
2  Viera  27      90    65
3  Phobe  18      60    78

In [32]:
new_student = [['Keane', '28', '80', '90']]
df2 = pd.DataFrame.from_records(new_student, columns = column_name)
df2

    Name Age Midterm Final
0  Keane  28      80    90

----------

In [33]:
df = df.append(df2, ignore_index = True)
df

    Name Age Midterm Final
0  James  25     100    87
1  Kafka  32      80    79
2  Viera  27      90    65
3  Phobe  18      60    78
4  Keane  28      80    90

# 8. 중복 Row 삭제

## (1) 겹치는 모든 Row 삭제

In [36]:
# 중복된 Row 추가하기
df = df.append(df2, ignore_index = True)
df

    Name Age Midterm Final
0  James  25     100    87
1  Kafka  32      80    79
2  Viera  27      90    65
3  Phobe  18      60    78
4  Keane  28      80    90
5  Keane  28      80    90
6  Keane  28      80    90

In [38]:
# Duplicated('column') : 해당 컬럼값이 중복되는 row가 있으면 True 반환
df.duplicated('Name')

0    False
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [67]:
# Duplicates() : 중복된 row 제거!!
df = df.drop_duplicates()

## (2) 특정 Column이 같은 Row 삭제

In [69]:
new_student = [['Phobe', '18', '60', '78']]
df2 = pd.DataFrame.from_records(new_student, columns = column_name)
df2

    Name Age Midterm Final
0  Phobe  18      60    78

In [70]:
df = df.append(df2, ignore_index = True)
df

    Name Age Midterm Final
0  James  25     100    87
1  Kafka  32      80    79
2  Viera  27      90    65
3  Phobe  18      60    78
4  Keane  28      80    90
5  Phobe  18      60    78

In [73]:
# 이름이 같은걸 제거, keep = first -> 처음걸 남김, last -> 나중걸 남김
df = df.drop_duplicates(['Name'], keep = 'first')
df

    Name Age Midterm Final
0  James  25     100    87
1  Kafka  32      80    79
2  Viera  27      90    65
3  Phobe  18      60    78
4  Keane  28      80    90

# 9. NaN값 찾기 & 바꾸기